 // Objeto con traducciones
const traducciones = {
    'es': {
        'formacionLabel': 'Informacion De Mi',
        'proyectoLabel': 'Proyectos Destacados',
        'habilidadLabel': 'Habilidades',
        'contactoLabel': 'Contacto',
        'ProyectoLabel': 'Proyectos Destacados',
        'acercaDeMiTexto': 'Como desarrollador junior, todos los proyectos destacados que encontrarás en mi portafolio han sido creados por mí. Estoy actualmente en una fase de aprendizaje y práctica, y cada uno de estos proyectos es significativo para mí, ya que representan mis primeros logros en este emocionante viaje de desarrollo.',
        'pythonLabel': 'Con el lenguaje de programación Python hice 2 proyectos:',
        'pythonProyecto1': 'Chatbot',
        'pythonProyecto2': 'Generador de Contraseñas',
        'javascriptLabel': 'Lenguaje de programación JavaScript, 2 proyectos:',
        'javascriptProyecto1': 'Generador de Citas',
        'javascriptProyecto2': 'Calculadora',
        'javaLabel': 'Lenguaje de programación Java, 2 proyectos:',
        'javaProyecto1': 'Tareas',
        'javaProyecto2': 'Tareas GUI',
        'htmlcssLabel': 'Lenguaje de programación HTML&CSS, 3 proyectos:',
        'htmlcssProyecto1': 'Mi Web Presentación',
        'htmlcssProyecto2': 'Login de Facebook (tomado en referencia)',
        'htmlcssProyecto3': 'Página de Contactos',
        'angularLabel': 'Lenguaje de programación Angular, 1 proyecto:',
        'angularProyecto1': 'Calculadora',
        'HabilidadLabel': 'Habilidades',
        'lenguajeLabel': 'Lenguajes de Programación:',
        'LenguajeLabel': 'Poseo conocimientos en diversos lenguajes de programación, entre ellos:',
        'lenguajeHabilidad1': 'Python',
        'lenguajeHabilidad2': 'JavaScript',
        'lenguajeHabilidad3': 'HTML&CSS',
        'lenguajeHabilidad4': 'PHP',
        'lenguajeHabilidad5': 'Java',
        'lenguajeHabilidad6': 'Angular',
        'desarrolloWeb': 'Desarrollo Web',
        'desarrolloWeb1': 'Experiencia en el desarrollo web utilizando HTML&CSS y JavaScript.',
        'desarrolloWeb2': 'Conocimiento en la creación de interfaces de usuario atractivas y funcionales.',
        'backend1': 'Familiaridad con el desarrollo en el lado del servidor, particularmente utilizando el framework Spring en Java.',
        'backend2': 'Capacidad para construir y mantener lógica de negocio robusta.',
        'baseDatos': 'Bases de Datos',
        'baseDatos1': 'Experiencia práctica con bases de datos, incluyendo MySQL y PostgreSQL.',
        'baseDatos2': 'Diseño y administración de bases de datos para garantizar un rendimiento eficiente.',
        'controlVersion': 'Control de Versiones:',
        'controlVersion1': 'Competencia en el uso de GIT para el control de versiones, permitiendo una colaboración efectiva en equipos de desarrollo.',
        'HerramientaU': 'Herramientas y Utilidades:',
        'HerramientaU1': 'Utilizado para mantener un código JavaScript limpio y coherente.',
        'HerramientaU2': 'Gestor de paquetes esencial para administrar dependencias y scripts en proyectos.',
        'HerramientaU3': 'Herramienta de autocompletado que mejora la productividad al escribir código.',
        'HerramientaU4': 'Herramientas esenciales para el desarrollo y depuración eficientes en entornos PHP.',
        'HerramientaU5': 'Utilizado para ejecutar servidores locales y facilitar el desarrollo en PHP.',
        'HerramientaU6': 'Proporciona evaluación en tiempo real y resultados de código para JavaScript y TypeScript, mejorando la calidad del código.',
        'objetivo': 'Objetivos',
        'objetivo1': 'Busco oportunidades para seguir desarrollando mis habilidades, aprender nuevas tecnologías y contribuir al éxito de proyectos innovadores.',
        'contacto': 'Contacto',
        // informacion.html
        'inicioLabel': 'Inicio',
        'acercaLabel': 'Acerca De Mi',
        'educacionLabel': 'Educacion',
        'capacitacionesLabel': 'Capacitaciones',
        'AcercaLabel': 'Acerca De Mi',
        'AcercaLabel1': 'Mi nombre es Enmanuel albornoz, soy venezolano y tengo 30 años. Inicialmente, me formé como ingeniero en mantenimiento mecánico, pero mi trayectoria ha evolucionado hacia el apasionante mundo de la programación web. En la actualidad, me desempeño como programador con habilidades tanto en el Front-end como en el Back-end.Considero mi nivel de conocimiento en el ámbito de la programación como junior, pero siempre estoy inmerso en un constante proceso de aprendizaje. Me encanta reforzar lo que ya he aprendido y explorar nuevas tecnologías. Mi capacidad para asimilar nuevos conocimientos de manera rápida y efectiva es una de mis fortalezas. Mi experiencia laboral abarca aproximadamente seis años en el sector petrolero, donde adquirí habilidades valiosas. Hace cerca de un año, decidí adentrarme en el fascinante mundo del desarrollo web, y actualmente estoy en búsqueda activa de mi primer empleo como programador. En el ámbito personal, mi pasión por la música y el interés por los deportes, especialmente las disciplinas como la MMA y Muay Thai, complementan mi perfil multidimensional. Estoy emocionado por la oportunidad de contribuir con mi experiencia y aprender más en el fascinante mundo de la programación!',
        'FormacionLabel': 'Formacion Academica',
        'UniversidadLabel': 'Universidad',
        'UniversidadLabel1': 'Politecnico Satiago Mariño',
        'localidadLabel': 'Localidad',
        'localidadLabel1': 'Cabimas, Edo Zulia, Venezuela',
        'tituloLabel': 'Titulo',
        'carreraLabel': 'Ingeniero En Mantenimiento Mecanico',
        'añoLabel': 'Año de Graduacion',
        'colegioLabel': 'Colegio',
        'LocalidadLabel': 'Localidad',
        'LocalidadLabel1': 'Cabimas, Edo-Zulia, Venezuela',
        'TituloLabel': 'Titulo',
        'LocalidadLabel': 'Bachiller En Ciencias',
        'CarreraLabel': 'Año de Graduacion',
        'capacitacionLabel': 'Capacitaciones',
        //boton language-selector
        'idioma': 'Selecciona el Idioma',
        'idiomaLabel1': 'Español',
        'idiomaLabel2': 'Ingles'
    },
    'en': {
        'formacionLabel': 'Information About Me',
        'proyectoLabel': 'Featured Projects',
        'habilidadLabel': 'Habilities',
        'contactoLabel': 'Contact',
        'ProyectoLabel': 'Featured Projects',
        'acercaDeMiTexto': 'As a junior developer, all the featured projects you will find in my portfolio have been created by me. I am currently in a phase of learning and practice, and each of these projects is significant to me as they represent my first achievements in this exciting development journey.',
        'pythonLabel': 'With the Python programming language, I made 2 projects:',
        'pythonProyecto1': 'Chatbot',
        'pythonProyecto2': 'Password Generator',
        'javascriptLabel': 'JavaScript programming language, 2 projects:',
        'javascriptProyecto1': 'Quote Generator',
        'javascriptProyecto2': 'Calculator',
        'javaLabel': 'Java programming language, 2 projects:',
        'javaProyecto1': 'Tasks',
        'javaProyecto2': 'Tasks GUI',
        'htmlcssLabel': 'HTML&CSS programming language, 3 projects:',
        'htmlcssProyecto1': 'My Presentation Website',
        'htmlcssProyecto2': 'Facebook Login (taken as a reference)',
        'htmlcssProyecto3': 'Contact Page',
        'angularLabel': 'Angular programming language, 1 project:',
        'angularProyecto1': 'Calculator',
        'HabilidadLabel': 'Habilities',
        'lenguajeLabel': 'Programming Languages',
        'LenguajeLabel': 'I have knowledge in  diverse programming languages among them:',
        'lenguajeHabilidad1': 'Python',
        'lenguajeHabilidad2': 'JavaScript',
        'lenguajeHabilidad3': 'HTML&CSS',
        'lenguajeHabilidad4': 'PHP',
        'lenguajeHabilidad5': 'Java',
        'lenguajeHabilidad6': 'Angular',
        'desarrolloWeb': 'Web Development',
        'desarrolloWeb1': 'I have experience in the web development using HTML&CSS and JavaScript',
        'desarrolloWeb2': 'I have knowledge in the create user interfaces attractive and functional ',
        'backend1': 'Familiarity with server-side development, particularly using the Spring framework in Java.',
        'backend2': 'Capacity to build and keep the business robust logic',
        'baseDatos': 'Data Base',
        'baseDatos1': 'Practic experience with data base, including MYSQL and PostgreSQL',
        'baseDatos2': 'Design and administration of database for guaranteeing an efficient performance',
        'controlVersion': 'version Control:',
        'controlVersion1': 'Proficiency in the use of GIT for version control, allowing effective collaboration in development teams.',
        'HerramientaU': 'Tools and Utilities:',
        'HerramientaU1': 'Used to maintain clean and consistent JavaScript code.',
        'HerramientaU2': 'Essential package manager to manage dependencies and scripts in projects.',
        'HerramientaU3': 'Autocompletion tool that improves productivity when writing code.',
        'HerramientaU4': 'Essential tools for efficient development and debugging in PHP environments.',
        'HerramientaU5': 'Used to run local servers and facilitate PHP development.',
        'HerramientaU6': 'Provides real-time evaluation and code results for JavaScript and TypeScript, improving code quality.',
        'objetivo': 'Objects',
        'objetivo1': 'I look for opportunities to continue developing my skills, learn new technologies and contribute to the success of innovative projects.',
        'contacto': 'Contact',
        //informacion.html
        'inicioLabel': 'Home',
        'acercaLabel': 'About Me',
        'educacionLabel': 'Education',
        'capacitacionesLabel': 'Training',
        'AcercaLabel': 'About Me',
        'AcercaLabel1': 'My name is Enmanuel, I am Venezuelan and I am 30 years old. Initially, I trained as a mechanical maintenance engineer, but my career has evolved towards the exciting world of web programming. Currently, I work as a programmer with skills in both Front-end and Back-end. I consider my level of knowledge in the field of programming as a junior, but I am always immersed in a constant learning process. I love reinforcing what I have already learned and exploring new technologies. My ability to assimilate new knowledge quickly and effectively is one of my strengths. My work experience spans approximately six years in the oil sector, where I acquired valuable skills. About a year ago, I decided to enter the fascinating world of web development, and I am currently actively searching for my first job as a programmer. On a personal level, my passion for music and interest in sports, especially disciplines such as MMA and Muay Thai, complement my multidimensional profile. I am excited for the opportunity to contribute my experience and learn more in the fascinating world of programming!',
        'FormacionLabel': 'Academic Training',
        'UniversidadLabel': 'University',
        'UniversidadLabel1': 'Politecnic Satiago Mariño',
        'localidadLabel': 'Location',
        'localidadLabel1': 'Cabimas, St. Zulia, Venezuela',
        'tituloLabel': 'Title',
        'carreraLabel': 'Mechanical Maintenance Engineer',
        'añoLabel': 'Year of Degree',
        'colegioLabel': 'Collegue',
        'LocalidadLabel': 'Location',
        'LocalidadLabel1': 'Cabimas, St. Zulia, Venezuela',
        'TituloLabel': 'Title',
        'LocalidadLabel': 'Bachelor of Sciences',
        'CarreraLabel': 'Year of Degree',
        'capacitacionLabel': 'Training',
        //boton language-selector
        'idioma': 'Select The Language',
        'idiomaLabel1': 'Spanish',
        'idiomaLabel2': 'English'
    }
};

    function cambiarIdioma() {
        const nuevoIdioma = document.getElementById('language').value;

        Object.keys(traducciones[nuevoIdioma]).forEach((clave) => {
            const elemento = document.getElementById(clave);
            if (elemento) {
                elemento.textContent = traducciones[nuevoIdioma][clave];
            }
        });

        document.documentElement.lang = nuevoIdioma;
    }
